# Generated by Django 3.0.5 on 2020-05-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_certificate_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="certificates.Hospital",
                verbose_name="Мед. учереждение",
            ),
        ),
    ]
