# Generated by Django 3.0.5 on 2020-05-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0004_auto_20200505_1029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="certificates.Hospital",
                verbose_name="Мед. учереждение",
            ),
        ),
    ]
