# Generated by Django 3.0.5 on 2020-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20200505_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='form',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Форма мед. документа'),
        ),
    ]
