# Generated by Django 3.0.5 on 2020-05-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_certificate_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('В обработке', 'In Processing'), ('Подтверждено', 'Confirmed'), ('Отклонено', 'Denied')], default='В обработке', max_length=30, verbose_name='Подтверждение'),
        ),
    ]
