# Generated by Django 3.0.5 on 2020-05-07 18:49

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_auto_20200507_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='additional_fields',
            field=django_extensions.db.fields.json.JSONField(default=dict, verbose_name='Дополнительые поля'),
        ),
    ]
