# Generated by Django 3.0.6 on 2020-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_certificate_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='short_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Краткое название формы'),
        ),
    ]
