# Generated by Django 3.0.5 on 2020-04-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
