# Generated by Django 3.0.5 on 2020-04-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20200430_2215'),
        ('main', '0002_auto_20200430_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.Hospital'),
        ),
    ]
