# Generated by Django 3.0.5 on 2020-05-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20200505_1032'),
        ('main', '0003_account_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.Hospital'),
        ),
    ]
